services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-11-07T00-52-20Z
    environment:
      - MINIO_REGION_NAME=local
      - MINIO_ROOT_USER=test
      - MINIO_ROOT_PASSWORD=testdslocal
    ports:
      - 9000:9000
    expose:
      - 9000
    command:
      - server
      - /data
